name: CMake CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v2
    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Configure CMake
      run: cmake -S . -B build
    - name: Build
      run: cmake --build build
    - name: Run tests
      run: cd build && ctest --output-on-failure
